version: '3'
services:
  mongodb:
    image: mongo:3.6.1
    container_name: mongodb
    volumes:
      - ./data:/data/db
      - ./data:/data/configdb
    ports:
      - 27017:27017
    command: mongod
volumes:
  mongodb: 
  mongodb_config: